# -*- coding: utf-8 -*-
"""Estrutura_de_repetição.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EPegYdu3Exjl0zLINdR-FX86lz86Vym4
"""



"""#Estrutura de repetição"""

#For Range
for contador in range(10):
    print(contador)

#for Range + break
for contador in range(1000):
    print(contador)
    if contador==2:
        break

lista= ['teste1',['teste2']]

# for simples
for val in lista:
  print(val)

# for com enumerate
for i,val in enumerate(lista):
  print(i,val)



"""for  com operadores compostos"""

lista2 = [2,3,4]

for val in lista2:
    val+=1
    print(val)

for val in lista2:
  val *=2
  print (val)

val=1
while (val<6):
  val *=2
  print(val)

